$CASEWORK_FRONTEND_DOMAIN = (ENV['CASEWORK_FRONTEND_DOMAIN'] || 'http://casework-frontend.landregistry.local')
$PROPERTY_FRONTEND_DOMAIN = (ENV['PROPERTY_FRONTEND_DOMAIN'] || 'http://property-frontend.landregistry.local') # not sure of local address yet
$MINT_API_DOMAIN = (ENV['MINT_API_DOMAIN'] || 'http://mint.landregistry.local') # not sure of local address yet
$SERVICE_FRONTEND_DOMAIN=(ENV['SERVICE_FRONTEND_DOMAIN'] || 'http://service-frontend.landregistry.local')
$LR_SEARCH_API_DOMAIN=(ENV['LR_SEARCH_API_DOMAIN'] || 'http://search-api.landregistry.local')
$SYSTEM_OF_RECORD_API_DOMAIN=(ENV['SYSTEM_OF_RECORD_API_DOMAIN'] || 'http://system-of-record.landregistry.local')
$LR_FIXTURES_URL=(ENV['LR_FIXTURES_URL'] || 'http://fixtures.landregistry.local')
$INTRODUCTIONS_DOMAIN = (ENV['INTRODUCTIONS_DOMAIN'] || 'http://introductions.landregistry.local')
$CASES_URL=(ENV['CASES_URL'] || 'http://cases.landregistry.local')
$HISTORIAN_URL=(ENV['HISTORIAN_URL'] || 'http://historian.landregistry.local')
